### ISSUE TITLE
Custom skies and environments.

### ISSUE THREAD

**Issue by Longor1996** [tiffit/TaleCraft#57]
It should be possible to change the way the sky looks, the color of fog, block lighting and more. Some of this is functionality already exists within the mod, but is not exposed to the user, yet.

To implement this, it should be possible to send a 'environment file' to (a (sub)set of) players.

### TODO

- [x] Add hooks for resource reloading.
- [x] Add parsing for environment json-file.
- [ ] Add rendering for environment from parsed file.
- [ ] Add predicate system for automatic environment selection.

**Comment by Longor1996** [comment]
New example file format, now with extra goodies!

```javascript
/*
  TaleCraft: Custom Environment System
  
  Note that environments are loaded trough resourcepacks,
  and are only visible to/on the client, not the server.
  
  The formatting in this file is such that
  all options for a property are listed one after another,
  with the name of the property.
  
  If multiple environments are active at the same time,
  the topmost one in this file is selected.
*/

/* a list of environments with names */
{
  env_default: null, /* default environment is minecraft:default */
  env_default: { /* default environment properties (see below) */ }
  
  /* a single environment */
  env_NAME: {
    /* when should the environment be used? */
    predicate: null, /* always */
    predicate: { /* under these conditions... */
      /* certain weather state? */
      weather: null,
      weather: ["clear", "rain", "thunder"],
      
      /* certain health? */
      health: null
      health: ["below", 100.0],
      health: ["at"   , 100.0],
      health: ["above", 100.0],
      
      /* certain score? */
      score: ["NAME", "below", 1],
      score: ["NAME", "at"   , 1],
      score: ["NAME", "above", 1],
      
      /* certain entity in range? */
      entity: {
        name: "dunkle", /* name of entity, or null */
        type: "Skeleton", /* type of entity, or null */
        range: 50.0 /* range to check for the entity */
      }
    },
    
    lighting: "talecraft:environments/example/lightmap.png"
    
    /* settings for distance fog? */
    fog: null,
    fog: {
      start: 1.0,
      end: 100.0,
      density: 0.1,
      color: [1.0, 1.0, 1.0]
    },
    
    /* settings for clouds? */
    clouds: null /*no clouds*/
    clouds: { /*one cloud layer*/
      angle: 360,
      speed: 1.0,
      height: 255,
      texture: "talecraft:environments/example/clouds.png"
    },
    clouds: [/*multiple cloud layers*/],
    
    sky: null, /* literally no sky at all */
    sky: { /* a single sky layer */
      /* what happens with the layer before this one? */
      blend: null, /* -> add */
      blend: "add",
      blend: "subtract",
      blend: "multiply",
      blend: "dodge",
      blend: "burn",
      blend: "screen",
      blend: "overlay",
      blend: "replace",
      blend: "alpha",
      
      fade: null, /* layer always visible */
      fade: { /* layer visible at certain times */
        out: {begin: "hh:mm", duration: "hh:mm"},
        out: {begin: "hh:mm", duration: "hh:mm"},
        in:  {begin: "hh:mm", end: "hh:mm"},
        in:  {begin: "hh:mm", end: "hh:mm"}
      }
      
      depth: null, /* -> false */
      depth: true, /* the sky has depth */
      depth: false, /* the sky has no depth */
      
      surface: null, /* -> color: white */
      surface: [1.0, 1.0, 1.0, 1.0], /* RGBA color */
      surface: "talecraft:environments/example/noise.png", /* texture */
      surface: { /* animation */
        frames: [/* list of textures */],
        timing: /* duration of frames */
      },
      
      shape: null, /* -> flat */
      shape: "cube", /* the classic 'skybox' */
      shape: "dome", /* the top part of a sphere cut in two */
      shape: "plane", /* a plane looking toward negative Z */
      shape: "sphere", /* a whole sphere */
      
      origin: null, /* -> player */
      origin: "player", /* origin is the player */
      origin: "world", /* origin is the world */
      origin: "eye", /* origin is the players eye */
      
      /* offset from the origin to place layer at. */
      offset: null, /* -> 0, 0, 0 */
      offset: [0.0, 0.0, 0.0],
      
      scale: null, /* -> 1.0 */
      scale:  [1.0, 1.0, 1.0],
      scale:  1.0,
      
      rotation: null, /* -> top, 0, 1 */
      rotation: {
        axis: "top",
        axis: "bottom",
        axis: "left",
        axis: "right",
        axis: "front",
        axis: "back",
        axis: [0.0, 1.0, 0.0],
        
        offset: 0.0, /*angle offset in degree; 0 to 360*/
        speed: 1.0 /*angle scale factor; can be 0 or higher*/
      },
      rotation: [/* multiple rotations */]
    },
    sky: [ /*one or more sky layers */]
  },
  
  /* there can up to 1000 individual environments */
}
```
